import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import EmotionProvider from "@/components/providers/emotion-provider";
import { CartProvider } from "@/components/context/cart-context";
import { UseMenu } from "@/utils/use-menu";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400",  "500", "700"],
});

export const metadata: Metadata = {
  title: "Huertabeja",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={poppins.className}>
        <EmotionProvider>
          <CartProvider>
            <UseMenu/>
            {children}
          </CartProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
