import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import EmotionProvider from "@/components/providers/emotion-provider";
import { AlertProvider } from "@/context/alert-context";
import { CardProvider } from "@/context/card-context";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400",  "500", "700"],
});

export const metadata: Metadata = {
  title: "Huertabeja",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={poppins.className}>
        <EmotionProvider>
          <AlertProvider>
            <CardProvider>
              {children}
            </CardProvider>
          </AlertProvider>
        </EmotionProvider>
      </body>
    </html>
  );
}
